linkedin_username: jonathonpyles
github_username: JNPyles

title: Jonathon Pyles
description: AI Development & Governance | CRCM | CERP
url: "https://jnpyles.github.io" 
author:
  name: Jonathon Pyles


# Tell GitHub Pages to use the SEO plugin
plugins:
  - jekyll-seo-tag


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# This tells Jekyll how to handle your site
theme: minima

collections:
  projects:
    output: true
    permalink: /projects/:title/

permalink: /:title/
highlighter: rouge

minima:
  skin: dark  # or "dark", "solarized", "solarized-dark"