linkedin_username: jonathonpyles
github_username: JNPyles

title: Jonathon Pyles
description: AI Development & Governance | CRCM | CERP
url: "https://jnpyles.com"
baseurl: ""

author:
  name: Jonathon Pyles


# Tell GitHub Pages to use the SEO plugin
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

show_drafts: true